[package]
name = "raytrace"
version = "0.1.0"
authors = ["Jack <jackbaude@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
serde = "1.0.126"
serde_derive = "1.0.126"